version: '3.8'

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}

networks:
  druid-net:
    driver: bridge

services:
  # =========================================
  # 1. ECOSSISTEMA KAFKA
  # =========================================
  zookeeper-kafka:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181" # Porta alterada para não conflitar com o ZK do Druid
    networks:
      - druid-net

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kafka:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-kafka
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Usa no máximo 1 núcleo do processador
          memory: 1G
    networks:
      - druid-net

  # =========================================
  # 2. ECOSSISTEMA DRUID
  # =========================================
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=druid
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    networks:
      - druid-net

  # Zookeeper dedicado ao Cluster Druid
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.10
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
    networks:
      - druid-net

  coordinator:
    image: apache/druid:34.0.0
    container_name: coordinator
    user: "0:0"
    volumes:
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/druid_shared:/opt/shared
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/coordinator_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Usa no máximo 1 núcleo do processador
          memory: 1G
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment
    networks:
      - druid-net

  broker:
    image: apache/druid:34.0.0
    container_name: broker
    user: "0:0"
    volumes:
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/broker_var:/opt/druid/var
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/druid_shared:/opt/shared
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Usa no máximo 1 núcleo do processador
          memory: 1G
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment
    networks:
      - druid-net

  historical:
    image: apache/druid:34.0.0
    container_name: historical
    user: "0:0"
    volumes:
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/druid_shared:/opt/shared
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/historical_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Usa no máximo 1 núcleo do processador
          memory: 1G
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment
    networks:
      - druid-net

  middlemanager:
    image: apache/druid:34.0.0
    container_name: middlemanager
    user: "0:0"
    volumes:
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/druid_shared:/opt/shared
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/middle_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    deploy:
      resources:
        limits:
          cpus: '1.0'    # Usa no máximo 1 núcleo do processador
          memory: 1G
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - environment
    networks:
      - druid-net

  router:
    image: apache/druid:34.0.0
    container_name: router
    user: "0:0"
    volumes:
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/router_var:/opt/druid/var
      - /home/gabriel/Documentos/UNIFEI/IC - DataOps/ApacheDruid/volumes/druid_shared:/opt/shared
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment
    networks:
      - druid-net

  # =========================================
  # 3. VISUALIZAÇÃO (SUPERSET)
  # =========================================
  superset:
    build: ./docker         # Caminho para a pasta do Dockerfile
    image: custom-superset:1.0   # Nome da sua imagem
    container_name: superset
    ports:
      - "8088:8088"
    networks:
      - druid-net
    environment:
      SUPERSET_SECRET_KEY: "minha-chave-secreta-ic-dataops-unifei"
    depends_on:
      - postgres
    restart: unless-stopped